jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Build
      run: 'chmod +x ./gradlew

        ./gradlew clean app:assembleDebug

        '
    - continue-on-error: true
      name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: ./app/build/outputs/apk/
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
